### ISSUE TITLE
Docs: suggest diesel_cli feature=sqlite

### ISSUE THREAD

**Issue by stchris** [alexwennerberg/gourami#14]
While following the installation steps I noticed that `diesel_cli` fails to install if you don't have dev headers for all the db libraries it supports (in my case: mysql). Maybe for the time being it would make sense to suggest installing it like this:

```$ cargo install diesel_cli --no-default-features --features "sqlite"```

**Comment by alexwennerberg** [comment]
Thanks for the catch!

**Comment by alexwennerberg** [comment]
Simplifying this process by embedding diesel migrations with https://docs.rs/diesel_migrations/1.4.0/diesel_migrations/macro.embed_migrations.html

**Comment by stchris** [comment]
Yes, that looks much cleaner 👍

**Comment by alexwennerberg** [comment]
Resolved in 46bb4c21a68ddc9cde58994ab55a88fecfdf7aa2
